### ISSUE TITLE
[Suggestion]: Fabric Support

### ISSUE THREAD

**Issue by ItzSkyReed** [Mrbysco/ItemFrament#1]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Is it possible to create a version that will work on fabric?

**Comment by Mrbysco** [comment]
Should be do-able

**Comment by ItzSkyReed** [comment]
That is nice! Thanks

**Comment by Mrbysco** [comment]
Which version would you like a fabric version for?

**Comment by ItzSkyReed** [comment]
1.20.4

**Comment by Mrbysco** [comment]
Done

**Comment by ItzSkyReed** [comment]
Thanks!!!!
